language: go
go:
  - 1.7
  - tip
before_script:
    - go get golang.org/x/tools/cmd/cover
    - go get github.com/mattn/goveralls
script: go test -race -v -covermode=atomic -coverprofile=coverage.txt .
after_success:    
    - bash <(curl -s https://codecov.io/bash)
    - $HOME/gopath/bin/goveralls -covermode=atomic -coverprofile=coverage.txt -service=travis-ci